version: 2.1
jobs:
  build:
    circleci_ip_ranges: true # opts the job into the IP ranges feature
    docker:
      - image: curlimages/curl
    steps:
      - run: curl ifconfig.me/ip
workflows:
  build-workflow:
    jobs:
      - build
